--
-- PostgreSQL database dump
--

\restrict oSxrlaEtyREfc0kg0kDdyM7hdhTXEuIAvTJy0RP7N08qmjK8edxgUGzrDOz8rJU

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg12+1)
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: inuka_db_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO inuka_db_user;

--
-- Name: pg_stat_statements; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;


--
-- Name: EXTENSION pg_stat_statements; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pg_stat_statements IS 'track planning and execution statistics of all SQL statements executed';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activities_activity; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.activities_activity (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    activity_type character varying(20) NOT NULL,
    activity_date date NOT NULL,
    photo character varying(100),
    tag character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    cohort_id uuid NOT NULL
);


ALTER TABLE public.activities_activity OWNER TO inuka_db_user;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO inuka_db_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: inuka_db_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO inuka_db_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: inuka_db_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO inuka_db_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: inuka_db_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO inuka_db_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO inuka_db_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: inuka_db_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: inuka_db_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO inuka_db_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: inuka_db_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cohorts_certification; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.cohorts_certification (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    issuing_body character varying(255) NOT NULL,
    awarded_date date,
    badge character varying(100),
    fellow_id uuid NOT NULL
);


ALTER TABLE public.cohorts_certification OWNER TO inuka_db_user;

--
-- Name: cohorts_cohort; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.cohorts_cohort (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    focus_area character varying(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    trainee_count integer NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT cohorts_cohort_trainee_count_check CHECK ((trainee_count >= 0))
);


ALTER TABLE public.cohorts_cohort OWNER TO inuka_db_user;

--
-- Name: cohorts_fellow; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.cohorts_fellow (
    id uuid NOT NULL,
    full_name character varying(255) NOT NULL,
    county character varying(100) NOT NULL,
    education_background character varying(255) NOT NULL,
    technical_interest character varying(255) NOT NULL,
    specialization character varying(255) NOT NULL,
    bio text NOT NULL,
    quote character varying(500) NOT NULL,
    placement_status character varying(20) NOT NULL,
    portfolio_url character varying(200) NOT NULL,
    photo character varying(100),
    is_featured boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    cohort_id uuid NOT NULL
);


ALTER TABLE public.cohorts_fellow OWNER TO inuka_db_user;

--
-- Name: content_galleryitem; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.content_galleryitem (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    media character varying(100) NOT NULL,
    media_type character varying(10) NOT NULL,
    caption character varying(500) NOT NULL,
    captured_date date,
    created_at timestamp with time zone NOT NULL,
    cohort_id uuid
);


ALTER TABLE public.content_galleryitem OWNER TO inuka_db_user;

--
-- Name: content_post; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.content_post (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    content text NOT NULL,
    category character varying(20) NOT NULL,
    cover_image character varying(100),
    is_published boolean NOT NULL,
    published_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    author_id integer
);


ALTER TABLE public.content_post OWNER TO inuka_db_user;

--
-- Name: content_sitesetting; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.content_sitesetting (
    id uuid NOT NULL,
    key character varying(100) NOT NULL,
    value text NOT NULL,
    description character varying(255) NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.content_sitesetting OWNER TO inuka_db_user;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO inuka_db_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: inuka_db_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO inuka_db_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: inuka_db_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO inuka_db_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: inuka_db_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO inuka_db_user;

--
-- Name: impact_metric; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.impact_metric (
    id uuid NOT NULL,
    key character varying(100) NOT NULL,
    label character varying(255) NOT NULL,
    value character varying(100) NOT NULL,
    unit character varying(50) NOT NULL,
    sort_order integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT impact_metric_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.impact_metric OWNER TO inuka_db_user;

--
-- Name: partners_partner; Type: TABLE; Schema: public; Owner: inuka_db_user
--

CREATE TABLE public.partners_partner (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    description text NOT NULL,
    logo character varying(100) NOT NULL,
    website_url character varying(200) NOT NULL,
    is_required_acknowledgement boolean NOT NULL,
    sort_order integer NOT NULL,
    focus_areas character varying(500) NOT NULL,
    CONSTRAINT partners_partner_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.partners_partner OWNER TO inuka_db_user;

--
-- Data for Name: activities_activity; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.activities_activity (id, title, description, activity_type, activity_date, photo, tag, created_at, cohort_id) FROM stdin;
23513902-8861-4ecf-8ada-ca0845b7c1db	Certification Preparation Programme	Structured preparation sessions for industry-recognised certifications in fibre optics.	workshop	2026-05-01	activities/cert_cgoewr	certification	2026-07-06 15:57:25.42+00	d6725c22-d0cd-486d-b272-27fde3482d7e
3990dc8b-27c6-4640-917a-dde87b4eef67	OTDR and Power Meter Practical Sessions	Trainees learn to operate optical time-domain reflectometers and power meters for fibre characterisation.	lab	2026-06-01	activities/OTDR_nvogjk	testing	2026-07-06 15:57:25.414+00	d6725c22-d0cd-486d-b272-27fde3482d7e
376f4967-53c2-46d6-b61e-2241cb5f80e8	Safety and Compliance Training	Essential training in workplace safety, PPE usage, and regulatory compliance.	workshop	2026-06-15	activities/safe_payskx	safety	2026-07-06 15:57:25.423+00	d6725c22-d0cd-486d-b272-27fde3482d7e
04946275-e761-4519-9196-c41394b57168	Hands-on Fibre Optic Splicing Lab	Trainees gain practical experience in fusion splicing, mechanical splicing, and connector termination.	lab	2026-06-20	activities/handson_la3ibw	fibre-optics	2026-07-06 15:57:25.411+00	d6725c22-d0cd-486d-b272-27fde3482d7e
4d39933a-b174-41e7-8c20-b23898e808ec	Portfolio Development Workshop	Trainees build professional portfolios showcasing their technical projects and certifications.	workshop	2026-06-25	activities/portfolio_ppx2li	career	2026-07-06 15:57:25.417+00	d6725c22-d0cd-486d-b272-27fde3482d7e
b717978a-81e6-438d-a32d-0e18a07e1af3	Industry Masterclasses with Leading Engineers	Senior engineers deliver intensive sessions on advanced topics in network infrastructure.	masterclass	2026-06-27	activities/masterclass_pbuzmu	masterclass	2026-07-06 15:57:25.419+00	d6725c22-d0cd-486d-b272-27fde3482d7e
b5af62cd-b0d1-4032-b0ad-a4fd40b1bc40	Field Demonstrations at Active Deployment Sites	Trainees visit live fibre deployment projects to observe cable blowing and aerial installation.	field_demo	2026-07-01	activities/field_crfx50	field	2026-07-06 15:57:25.415+00	d6725c22-d0cd-486d-b272-27fde3482d7e
03dab206-dce2-4ef7-bf73-da60e7a2f5c3	Network Infrastructure Design Lab	Trainees design fibre optic network layouts and calculate link budgets.	lab	2026-07-15	activities/fielddemo_galocn	design	2026-07-06 15:57:25.421+00	d6725c22-d0cd-486d-b272-27fde3482d7e
e1095eb6-ed61-4b88-9b62-c2cc54738d5b	Broadband Deployment and Last-Mile Connectivity	Focused training on broadband network deployment strategies for underserved areas.	lab	2026-09-01	activities/netinfrastructure_fj4f4p	broadband	2026-07-06 15:57:25.424+00	d6725c22-d0cd-486d-b272-27fde3482d7e
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add cohort	7	add_cohort
26	Can change cohort	7	change_cohort
27	Can delete cohort	7	delete_cohort
28	Can view cohort	7	view_cohort
29	Can add fellow	8	add_fellow
30	Can change fellow	8	change_fellow
31	Can delete fellow	8	delete_fellow
32	Can view fellow	8	view_fellow
33	Can add certification	9	add_certification
34	Can change certification	9	change_certification
35	Can delete certification	9	delete_certification
36	Can view certification	9	view_certification
37	Can add activity	10	add_activity
38	Can change activity	10	change_activity
39	Can delete activity	10	delete_activity
40	Can view activity	10	view_activity
41	Can add site setting	11	add_sitesetting
42	Can change site setting	11	change_sitesetting
43	Can delete site setting	11	delete_sitesetting
44	Can view site setting	11	view_sitesetting
45	Can add gallery item	12	add_galleryitem
46	Can change gallery item	12	change_galleryitem
47	Can delete gallery item	12	delete_galleryitem
48	Can view gallery item	12	view_galleryitem
49	Can add post	13	add_post
50	Can change post	13	change_post
51	Can delete post	13	delete_post
52	Can view post	13	view_post
53	Can add metric	14	add_metric
54	Can change metric	14	change_metric
55	Can delete metric	14	delete_metric
56	Can view metric	14	view_metric
57	Can add partner	15	add_partner
58	Can change partner	15	change_partner
59	Can delete partner	15	delete_partner
60	Can view partner	15	view_partner
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$720000$7Wvs6u0o1oi97nPeYkkYbL$PK2RRB9x7NjqICObvDuHFzUhT/KhR5t57QtjuoWiQBY=	2026-08-03 06:30:54.096788+00	t	admin			admin@inuka.co.ke	t	t	2026-07-17 08:43:21.83414+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: cohorts_certification; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.cohorts_certification (id, name, issuing_body, awarded_date, badge, fellow_id) FROM stdin;
\.


--
-- Data for Name: cohorts_cohort; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.cohorts_cohort (id, name, focus_area, start_date, end_date, trainee_count, status, created_at) FROM stdin;
56610bcc-90b4-4e50-b2ff-e8e85c49e5e7	Cohort 2	Cybersecurity & Cloud	2026-07-07	2026-07-07	30	upcoming	2026-07-07 07:21:53.735+00
d6725c22-d0cd-486d-b272-27fde3482d7e	Cohort 1	FibreOptic	2026-07-07	2026-12-07	15	active	2026-07-06 15:36:39.894+00
\.


--
-- Data for Name: cohorts_fellow; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.cohorts_fellow (id, full_name, county, education_background, technical_interest, specialization, bio, quote, placement_status, portfolio_url, photo, is_featured, created_at, cohort_id) FROM stdin;
9b431b49-a1d0-4824-b72e-dfc99835ab4f	Elvis  Ochieng	Nairobi	Telecommunication & Information Engineering	Network Defense, Networking	Fibre Optic Engineering	Telecommunication Engineer currently working as an Optical Fibre Technician at Inuka Tech Fellow, Kenya Pipeline Company PLC (Jun 2026 – Present).	Inuka is more than a fellowship; it is the engineering blueprint where raw technical potential is wired into the robust infrastructure of a digital economy.	in_training		fellows/Elvis_Ochieng_z5bsfi	t	2026-07-30 09:28:17.061177+00	d6725c22-d0cd-486d-b272-27fde3482d7e
9307ccd2-9ea3-4a4f-ac08-5073526eca20	Emmanuel Ruhusa	Mombasa	Electrical & Telecommunication Engineer	Electrical & Telecommunication Engineering	Fibre Optic Engineering	Telecommunication Engineer and IT Support Certified specialist based in Mombasa, with a passion for IoT, Network Systems, and Data Center Automation	The Inuka Digital Leap isn't just about connecting devices; it's about connecting potential. Through the KPC Foundation, we are turning raw engineering talent into the infrastructure that will power Kenya's digital future, ensuring no young mind is left offline.	in_training		fellows/Emmanuel_Ruhusa_tnrnzq	t	2026-07-30 09:56:25.921537+00	d6725c22-d0cd-486d-b272-27fde3482d7e
c76de266-98ce-4c87-b9c9-aacc07e1d2b9	Nicole Atieno	Nairobi	Computer Science, Web Designing	Optical fiber communication, backbone transport networks, signal transmission systems, and fiber fault detection.	Fibre Optic Engineering	Learning fibre optic splicing and testing has given me a career I never imagined.	Grateful to the Inuka Tech Fellowship and JHUB Africa for this unique opportunity to deepen my expertise in optical fiber technology. It’s an honor to contribute to Kenya's digital infrastructure while sharpening the skills needed to protect it	in_training		fellows/Nicole_Atieno_fmhl6k	t	2026-07-30 09:22:06.855309+00	d6725c22-d0cd-486d-b272-27fde3482d7e
a2c94202-9ebf-46d3-90a7-f190fe4af593	Khadija Jelle	Nairobi	ICT & Network Support Specialist	Embedded Systems, AI-driven Engineering, and IoT Development.	Fibre Optic Engineering	I am a dedicated Cybersecurity Analyst with 2+ years of hands-on experience in ICT and digital systems. I’ve worked on system support, cybersecurity awareness, and monitoring & evaluation combining both technical and strategic thinking.	Fibre optics is the artery of our digital future, carrying the pulse of connectivity across Kenya. But as we accelerate through the digital leap, speed means nothing without security. My commitment is to ensure that every light signal traveling through these cables is not just fast, but fortified against the unseen threats of the cyber world.	in_training		fellows/khadija_jelle_Abdi_roqjyq	t	2026-07-30 10:04:20.221687+00	d6725c22-d0cd-486d-b272-27fde3482d7e
7f58cb5b-99dd-46bb-a8ec-0ba22933a4c1	John Ndungu Kiarie	Nairobi	Cybersecurity Analyst	Security Research, Security Consulting, Cyber Security Risk Management.	Fibre Optic Engineering	I’m a Computer Science graduate passionate about cybersecurity and digital protection.\r\nDuring my internship  at Amref Health Africa and experience in Huawei Seeds for the future, I’ve gained hands-on experience in network security, VPNs, system support, AccessControl and Firewalls	Inuka is not just a fellowship; it is the spark that ignites the journey from potential to power, transforming raw technical curiosity into the disciplined resilience needed to safeguard Africa's digital future.	in_training		fellows/John_Ndungu_offund	t	2026-07-30 09:49:51.063798+00	d6725c22-d0cd-486d-b272-27fde3482d7e
1030c692-a104-47e4-a2a5-7cc58b10c0ca	Samwel Chege Mwangi	Nairobi	Telecommunication Engineering	fibre installation, fusion splicing, OTDR testing, fault diagnosis,	Fibre Optic Engineering	I am a Telecommunications and Information Technology graduate with a strong interest in optical fibre networks, networking, and ICT infrastructure. I enjoy solving technical problems, learning new technologies, and applying practical skills to real-world projects.	Connecting the nation's energy flow with precision and integrity, just as we splice fiber optics to keep the world connected. Moving Kenya forward, one pipeline at a time.	in_training		fellows/Samuel_Mwangi_ptqtpi	t	2026-07-30 09:34:42.513272+00	d6725c22-d0cd-486d-b272-27fde3482d7e
9a454fe5-cd90-4c0f-a241-03c85fabfc8b	Sylvia Chebwogen	Nairobi	Information Technology	Information and Communications Technology (ICT), Artificial Intelligence (AI)	Fibre Optic Engineering	As I navigate my journey at JKUAT, my focus remains on leveraging AI and prompt engineering to bridge the gap between technology and community needs	Inuka Digital is more than a name; it is a call to rise above the noise and build a future where technology serves the community. By merging local ingenuity with global innovation, we don't just adapt to the digital age—we define it.	in_training		fellows/sylvia_chebwogen_ztqrdt	t	2026-07-30 09:44:58.251314+00	d6725c22-d0cd-486d-b272-27fde3482d7e
552edbf3-adf7-4df4-ae07-b80ef44fc4ed	Byron Onyango Odongo	Nyanza	Electrical and Electronics Engineering	Industrial Control • I&C • Electrical & Instrumentation • Process Instrumentation • Control Station	Fibre Optic Engineering	Electrical and Instrumentation Engineer based in Nairobi, Kenya, specializing in industrial control systems, process instrumentation, and automation.	Before the Inika Digital Leap KPC program, my technical journey felt like navigating a map with missing pieces. Today, thanks to the rigorous training and the collaborative spirit of the KPC community, I don't just see the future of tech—I'm building it. This program didn't just teach me code; it gave me the confidence to leap from theory to real-world impact, turning every challenge into an opportunity to innovate.	in_training		fellows/Onyango_Bryon_Odongo_boninm	t	2026-07-30 13:49:04.388572+00	d6725c22-d0cd-486d-b272-27fde3482d7e
fc27774c-34b5-4968-982a-0e97aa610587	Ezra Mageto	Nairobi	ICT Infrastructure	Fibre Optics	Fibre Optic Engineering	A dedicated ICT Support Specialist with extensive experience in data analysis and computer networking, I am passionate about leveraging technology to solve complex problems and drive organizational success. My expertise spans across various domains, including technical support, data management, and network infrastructure	Just as Inuka calls us to rise, fibre optics are the rising arteries of Kenya's digital future. By weaving robust data analysis into the very strands of our network, we don't just connect businesses; we elevate them to a speed where innovation never waits. True ICT support isn't just about keeping the lights on—it's about ensuring the data that drives our economy flows as fast as the vision of those who rise	in_training		fellows/Ezra_Mageto_ohloh3	t	2026-07-30 13:55:58.587275+00	d6725c22-d0cd-486d-b272-27fde3482d7e
dea270b2-62f7-449d-ab50-42d0c4655f6f	Jemmimah Kananu	Nairobi	Telecommunications and Information Engineering	Optical fiber training, IT Support (implied through connections and field), Cybersecurity	Fibre Optic Engineering	Telecommunications and Information Engineering student based in Nairobi County, Kenya.	"Through the Inuka Digital Leap program at Kenya Pipeline Company, I have been able to strengthen my practical skills in optical fiber deployment and network infrastructure, bridging the gap between my academic theory in Telecommunications and Information Engineering and real-world application.	in_training		fellows/Jemmimah_Kananu_mwithali_bghkxt	t	2026-07-30 14:04:45.262947+00	d6725c22-d0cd-486d-b272-27fde3482d7e
4033544b-1732-4c48-a80e-b53310a28f2b	Peter  Njuguna	Kiambu	Electrical  Engineer	Technical Architecture	Fibre Optic Engineering	Passionate about events planning, coding, and research. Skilled in academic writing, MATLAB/Multisim simulation, and C++	Digital infrastructure is more than cables and equipment—it's about connecting communities, creating opportunities, and building Kenya's future one network at a time.	in_training		fellows/Peter_Njuguna_njce2a	t	2026-07-30 14:22:16.371264+00	d6725c22-d0cd-486d-b272-27fde3482d7e
92a503de-8713-4680-a955-e3efe8e22af1	Nicole Alice	Nairobi	Electronics and Computer  Engineering	Fiber Technician	Fibre Optic Engineering	An aspiring technology professional with a passion for leveraging digital solutions to create meaningful impact	The Inuka Digital Leap Programme has shown me that digital infrastructure is more than technology—it's about creating opportunities, connecting communities, and building a more inclusive digital future for Kenya	in_training		fellows/Nicole_Alex_Smith_te2b1q	t	2026-07-30 14:30:43.539759+00	d6725c22-d0cd-486d-b272-27fde3482d7e
0dd031f5-df57-4106-a8f8-98c6c6f9359d	Irene  Yegon	Nairobi	Telecommunications Engineer	Machine Learning,IoT	Fibre Optic Engineering	Digital infrastructure professional with a growing interest in telecommunications, network engineering, and emerging technologies.	The Inuka Digital Leap Kenya Pipeline Programme has shown me that every fibre connection is more than infrastructure—it is an opportunity to connect people, empower communities, and shape Kenya's digital future	in_training		fellows/Irene_Chelimo_xtyejr	t	2026-07-30 14:36:34.771654+00	d6725c22-d0cd-486d-b272-27fde3482d7e
bfe4c0f6-7354-4726-b4f6-cd792d96c440	Wendy Angela Anyango	Nairobi	Telecommunications Technician	Telecommunications Engineering	Fibre Optic Engineering	I am a Telecommunications Engineering student with hands-on experience in telecommunications systems, fiber optic networks, and network infrastructure	The Inuka Digital Leap Kenya Pipeline Programme has shown me that every connection we build goes beyond technology—it creates opportunities, empowers communities, and inspires the next generation of innovators	in_training		fellows/Wendy_Angela_Anyango_rlitxa	t	2026-07-30 14:50:44.558679+00	d6725c22-d0cd-486d-b272-27fde3482d7e
806da3c2-cdcd-4bac-b89b-6139ef207d63	Adan Onyancha	Nairobi	Electronic & Computer Engineering	Embedded Systems, Real-time simulators Development.	Fibre Optic Engineering	​I am an Electronics and Computer Engineering student with a solid background in both hardware and software development. My experience ranges from circuit design and electrical systems to programming in C, C++, and Python. I enjoy working on embedded systems, network infrastructure, and applying data analytics to solve practical technical problems.\r\n​Always looking to connect with professionals and peers in the electronics, electrical, and software engineering space.	The Inuka Digital Leap Kenya Pipeline Programme has shown me that technology is more than writing code—it's about building the infrastructure that connects people, creates opportunities, and transforms communities	in_training		fellows/Adan_Onyancha_gv1ics	t	2026-07-30 14:55:02.396364+00	d6725c22-d0cd-486d-b272-27fde3482d7e
\.


--
-- Data for Name: content_galleryitem; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.content_galleryitem (id, title, media, media_type, caption, captured_date, created_at, cohort_id) FROM stdin;
\.


--
-- Data for Name: content_post; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.content_post (id, title, slug, content, category, cover_image, is_published, published_at, created_at, author_id) FROM stdin;
4378ba73-d2a3-48d8-87d7-345d2d272a22	JKUAT and JHUB Africa Sign MoU to Expand Digital Skills Programme	jkuat-and-jhub-africa-sign-mou-to-expand-digital-skills-programme	Jomo Kenyatta University of Agriculture and Technology and JHUB Africa have signed a renewed Memorandum of Understanding that expands the Inuka Digital Leap programme to four additional counties. The expanded partnership will establish new training centres in Kisumu, Nakuru, Meru, and Mombasa.	news	posts/signmemo_zo3tdx	t	2026-07-06 15:57:06+00	2026-07-06 15:57:06.297+00	1
40d07af2-fadc-470f-a103-f9fe64fafd49	Why Fibre Optics is the Next Frontier for Kenya's Youth	why-fibre-optics-is-the-next-frontier-for-kenyas-youth	Kenya's digital transformation is being built on a foundation of fibre optics. As the government pushes forward with its ambitious national fibre rollout, the demand for skilled fibre optic technicians has skyrocketed. The Inuka Digital Leap programme is helping to fill this gap by providing practical, industry-aligned training in fibre optic engineering.	blog	posts/inukafellows_asu9ku	t	2026-07-06 15:57:06+00	2026-07-06 15:57:06.293+00	1
2791f15a-e70d-4164-baa5-b4671c06cea9	Kenya Pipeline Foundation Commits to Digital Skills Development	kenya-pipeline-foundation-commits-to-digital-skills-development	The Kenya Pipeline Foundation has announced a significant commitment to expanding the Inuka Digital Leap programme, pledging resources to scale the initiative to reach more young Kenyans across additional counties. This partnership will focus on addressing the critical skills gap in fibre optics engineering, a field experiencing unprecedented demand as Kenya accelerates its national fibre rollout.	news	posts/partneship_hyqd4c	t	2026-07-06 15:57:06+00	2026-07-06 15:57:06.289+00	1
5c00bf4e-c9f2-4962-bd6b-fc89dcb821f2	Cohort 1 Trainees Begin Industry Attachments Across Kenya	cohort-1-trainees-begin-industry-attachments-across-kenya	The trainees of Cohort 1 have commenced their industry attachments with partner organisations across Kenya, marking the final phase of the Inuka Digital Leap programme. Each trainee has been assigned to a host organisation that aligns with their area of specialisation.	news	posts/cohort1_midhbl	t	2026-07-06 15:57:06+00	2026-07-06 15:57:06.303+00	1
227200d2-661d-40f0-9e84-581b024ab10b	Community Outreach: Digital Literacy Workshop in Kiambu County	community-outreach-digital-literacy-workshop-in-kiambu-county	Trainees from the Inuka Digital Leap programme led a digital literacy workshop for local youth in Kiambu County. The workshop covered topics such as basic internet navigation, online safety, and career pathways in technology.	blog	posts/communityoutreach_xrwjkx	t	2026-07-06 15:57:06+00	2026-07-06 15:57:06.304+00	1
8f026c8a-d01d-4f69-a1ff-47b250d67269	Industry Mentors Share Insights on Kenya's Digital Infrastructure Future	industry-mentors-share-insights-on-kenyas-digital-infrastructure-future	The Inuka Digital Leap programme hosted a mentorship forum featuring senior engineers and technology leaders from Kenya's leading telecommunications companies including Safaricom, Telkom Kenya, and several fibre network operators.	blog	posts/industryExperts_bovhga	t	2026-07-06 15:57:06+00	2026-07-06 15:57:06.301+00	1
f0b17c7a-97f6-4728-bb29-32fe4c5946c9	Field Visit: Trainees Experience Real-World Fibre Deployment	field-visit-trainees-experience-real-world-fibre-deployment	The trainees of Cohort 1 stepped out of the classroom and into the field for an immersive day of learning at active fibre deployment sites across Nairobi. The field visit gave trainees a firsthand look at real-world network deployment operations.	news	posts/fielddemo_hbjvd4	t	2026-07-06 15:57:06+00	2026-07-06 15:57:06.3+00	1
92955bcd-2c31-49f8-9832-1543984d2666	Women in Tech: Breaking Barriers in Network Infrastructure	women-in-tech-breaking-barriers-in-network-infrastructure	With 42% female representation in its first cohort, the Inuka Digital Leap programme is demonstrating that gender inclusion is not just a goal but an achievable reality. The trainees are thriving in what has historically been a male-dominated technical field.	blog	posts/womenintech_lzhutq	t	2026-07-06 15:57:06+00	2026-07-06 15:57:06.298+00	1
efcefd86-67b8-4402-aedc-5f519b619324	Trainees Complete First Round of Fibre Optic Splice Certification	trainees-complete-first-round-of-fibre-optic-splice-certification	All 15 members of Cohort 1 have successfully passed their Fibre Optic Splice Certification examination. The practical examination, administered by certified industry assessors, tested the trainees proficiency in fusion splicing, mechanical splicing, and connector termination. The pass rate of 100% reflects both the dedication of the trainees and the effectiveness of the programme hands-on training approach.	news	posts/firstcertification_u8qicr	t	2026-07-06 15:57:06+00	2026-07-06 15:57:06.295+00	1
e0adf7d8-a851-487a-ae5d-3cac74b07116	Inuka Digital Leap First Cohort of 15 Trailblazers	inuka-digital-leap-first-cohort-of-15-trailblazers	The Inuka Digital Leap Programme marked a defining milestone with the formation of its inaugural cohort of 15 trainees, who successfully applied, were selected, and formally enrolled into the intensive training pathway on June 15, 2026. The cohort represents the first intake under the programme structured digital workforce development framework. The launch and recognition event, hosted at the Jomo Kenyatta University of Agriculture and Technology (JKUAT) Main Campus, brought together stakeholders from industry, government, and the families of the trainees to acknowledge the significance of this pioneering group. Over a six-month period, Cohort 1 underwent rigorous, competency-based training covering network infrastructure, fibre optic engineering, broadband deployment, and cloud engineering.	news	posts/fellows_k8djix	t	2026-07-06 15:38:59+00	2026-07-06 15:38:59.628+00	1
\.


--
-- Data for Name: content_sitesetting; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.content_sitesetting (id, key, value, description, updated_at) FROM stdin;
0f861174-00ff-4b20-b500-003248b9b413	footer_acknowledgement	THIS PROJECT IS SUPPORTED BY KPC FOUNDATION	Required footer acknowledgement text	2026-07-06 15:57:42.567+00
db71e8e4-5a5c-489a-9a39-e1cafbe59f97	pathway_steps	[{"step": 1, "title": "Selection", "description": "Rigorous identification of high-potential youth from partner counties across Kenya.", "icon": "pi pi-search", "status": "completed"}, {"step": 2, "title": "Onboarding", "description": "Orientation, needs assessment, and personalised learning plans for each trainee.", "icon": "pi pi-user-plus", "status": "active"}, {"step": 3, "title": "Technical Training", "description": "Classroom and lab-based sessions covering fibre fundamentals, network architecture, and broadband systems.", "icon": "pi pi-wrench", "status": "upcoming"}, {"step": 4, "title": "Industry Attachment", "description": "Structured placement with industry partners where trainees apply their learning.", "icon": "pi pi-briefcase", "status": "upcoming"}, {"step": 5, "title": "Deployment", "description": "Graduates deployed across Kenya's digital infrastructure projects.", "icon": "pi pi-flag", "status": "upcoming"}]	Programme pathway steps	2026-07-06 15:57:42.565+00
2f6c5a43-34f7-48c0-98e5-efd0f2eafe55	learning_areas	[{"title": "Network & Fixed Broadband Foundations", "description": "Core principles of network architecture, broadband technologies, and infrastructure fundamentals.", "icon": "pi pi-sitemap"}, {"title": "Optical Fibre Fundamentals", "description": "Physics of light propagation, fibre types, cable construction, and transmission principles.", "icon": "pi pi-sun"}, {"title": "Fibre Survey, Planning & Documentation", "description": "Route surveying, network design, GIS mapping, and as-built documentation.", "icon": "pi pi-pencil"}, {"title": "Installation, Splicing & Testing", "description": "Cable blowing, fusion splicing, connectorisation, OTDR testing, and power meter measurements.", "icon": "pi pi-wrench"}, {"title": "Maintenance & Service Restoration", "description": "Fault diagnosis, restoration techniques, preventive maintenance, and network resilience strategies.", "icon": "pi pi-refresh"}, {"title": "Digitization & Automation", "description": "Digital tools for network management, automated monitoring systems, and smart infrastructure.", "icon": "pi pi-cog"}, {"title": "Occupational Health & Safety", "description": "Worksite safety, hazard identification, PPE usage, and confined space procedures.", "icon": "pi pi-shield"}, {"title": "Customer Service & Professional Conduct", "description": "Client communication, professional ethics, teamwork, and workplace professionalism.", "icon": "pi pi-users"}]	Learning areas displayed on the pathway page	2026-07-06 15:57:42.562+00
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-07-30 03:25:11.446565+00	22222222-2222-2222-2222-222222222202	JKUAT	2	[{"changed": {"fields": ["Logo"]}}]	15	1
2	2026-07-30 03:26:18.42535+00	22222222-2222-2222-2222-222222222203	JHUB Africa	2	[{"changed": {"fields": ["Logo"]}}]	15	1
3	2026-07-30 03:29:52.335893+00	23513902-8861-4ecf-8ada-ca0845b7c1db	Certification Preparation Programme	2	[{"changed": {"fields": ["Photo"]}}]	10	1
4	2026-07-30 03:32:17.758151+00	227200d2-661d-40f0-9e84-581b024ab10b	Community Outreach: Digital Literacy Workshop in Kiambu County	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
5	2026-07-30 03:32:57.553511+00	5c00bf4e-c9f2-4962-bd6b-fc89dcb821f2	Cohort 1 Trainees Begin Industry Attachments Across Kenya	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
6	2026-07-30 03:33:25.598786+00	8f026c8a-d01d-4f69-a1ff-47b250d67269	Industry Mentors Share Insights on Kenya's Digital Infrastructure Future	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
7	2026-07-30 03:35:18.586645+00	f0b17c7a-97f6-4728-bb29-32fe4c5946c9	Field Visit: Trainees Experience Real-World Fibre Deployment	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
8	2026-07-30 03:36:23.165659+00	92955bcd-2c31-49f8-9832-1543984d2666	Women in Tech: Breaking Barriers in Network Infrastructure	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
9	2026-07-30 03:37:28.442734+00	4378ba73-d2a3-48d8-87d7-345d2d272a22	JKUAT and JHUB Africa Sign MoU to Expand Digital Skills Programme	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
10	2026-07-30 03:38:10.690495+00	efcefd86-67b8-4402-aedc-5f519b619324	Trainees Complete First Round of Fibre Optic Splice Certification	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
11	2026-07-30 03:38:54.122722+00	40d07af2-fadc-470f-a103-f9fe64fafd49	Why Fibre Optics is the Next Frontier for Kenya's Youth	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
12	2026-07-30 03:39:25.989604+00	2791f15a-e70d-4164-baa5-b4671c06cea9	Kenya Pipeline Foundation Commits to Digital Skills Development	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
13	2026-07-30 03:42:49.77094+00	e0adf7d8-a851-487a-ae5d-3cac74b07116	Inuka Digital Leap First Cohort of 15 Trailblazers	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
14	2026-07-30 03:45:10.805777+00	22222222-2222-2222-2222-222222222202	JKUAT	2	[{"changed": {"fields": ["Focus areas"]}}]	15	1
15	2026-07-30 03:47:07.047067+00	22222222-2222-2222-2222-222222222202	Jomo Kenyatta University of Agriculture and Technology	2	[{"changed": {"fields": ["Name", "Description", "Focus areas"]}}]	15	1
16	2026-07-30 03:48:24.068898+00	22222222-2222-2222-2222-222222222203	JHUB Africa	2	[{"changed": {"fields": ["Description", "Focus areas"]}}]	15	1
17	2026-07-30 06:35:02.346403+00	09c86958-4e09-4a49-bf6f-33808a84e518	Amina Said	2	[{"changed": {"fields": ["Photo"]}}]	8	1
18	2026-07-30 08:45:04.62272+00	09c86958-4e09-4a49-bf6f-33808a84e518	Nicole Atieno	2	[{"changed": {"fields": ["Full name", "County", "Education background", "Photo"]}}]	8	1
19	2026-07-30 08:48:10.790778+00	09c86958-4e09-4a49-bf6f-33808a84e518	Nicole Atieno	2	[{"changed": {"fields": ["Quote"]}}]	8	1
20	2026-07-30 09:20:31.24051+00	09c86958-4e09-4a49-bf6f-33808a84e518	Amina Said	3		8	1
21	2026-07-30 09:20:31.244788+00	db030754-1d60-4524-b375-078107e4ef7e	Brian Kiprop	3		8	1
22	2026-07-30 09:20:31.247468+00	1fbef470-52b1-48cc-88eb-55d7a904651b	Daniel Mwangi	3		8	1
23	2026-07-30 09:20:31.250224+00	d89c423e-3961-4fa9-bcaa-86e2e4db6547	Esther Chebet	3		8	1
24	2026-07-30 09:20:31.252867+00	4f64f3a0-27d1-4e8d-9e23-df0de1625cc8	Fatima Hassan	3		8	1
25	2026-07-30 09:20:31.255545+00	41aa0f78-f681-4554-9af2-a982456c56a1	Grace Akinyi	3		8	1
26	2026-07-30 09:20:31.258057+00	18e9fa65-5582-415b-b56b-906bc953cc37	James Kiprono	3		8	1
27	2026-07-30 09:20:31.260405+00	4cbbac71-1f3b-4b38-bb1f-8b7d8d95519e	Kevin Mboya	3		8	1
28	2026-07-30 09:20:31.262727+00	ac4180dc-d23c-4d7d-897c-8b39e6aaf23b	Nancy Akoth	3		8	1
29	2026-07-30 09:20:31.266044+00	19a63d40-529b-4feb-b06d-5bf0d6a8b211	Peter Otieno	3		8	1
30	2026-07-30 09:20:31.268483+00	769b9355-a49d-40e5-9016-2d44a525eee9	Sarah Wanjiku	3		8	1
31	2026-07-30 09:22:06.862941+00	c76de266-98ce-4c87-b9c9-aacc07e1d2b9	Nicole Atieno	1	[{"added": {}}]	8	1
32	2026-07-30 09:22:37.599442+00	c76de266-98ce-4c87-b9c9-aacc07e1d2b9	Nicole Atieno	2	[{"changed": {"fields": ["Is featured"]}}]	8	1
33	2026-07-30 09:28:17.063837+00	9b431b49-a1d0-4824-b72e-dfc99835ab4f	Elvis  Ochieng	1	[{"added": {}}]	8	1
34	2026-07-30 09:34:42.519825+00	1030c692-a104-47e4-a2a5-7cc58b10c0ca	Samwel Chege Mwangi	1	[{"added": {}}]	8	1
35	2026-07-30 09:44:58.256447+00	9a454fe5-cd90-4c0f-a241-03c85fabfc8b	Sylvia Chebwogen	1	[{"added": {}}]	8	1
36	2026-07-30 09:49:51.065325+00	7f58cb5b-99dd-46bb-a8ec-0ba22933a4c1	John Ndungu Kiarie	1	[{"added": {}}]	8	1
37	2026-07-30 09:56:25.925801+00	9307ccd2-9ea3-4a4f-ac08-5073526eca20	Emmanuel Ruhusa	1	[{"added": {}}]	8	1
38	2026-07-30 10:04:20.223213+00	a2c94202-9ebf-46d3-90a7-f190fe4af593	Khadija Jelle	1	[{"added": {}}]	8	1
39	2026-07-30 13:21:31.32854+00	9a454fe5-cd90-4c0f-a241-03c85fabfc8b	Sylvia Chebwogen	2	[{"changed": {"fields": ["Specialization"]}}]	8	1
40	2026-07-30 13:27:20.89281+00	09c86958-4e09-4a49-bf6f-33808a84e518	Amina Said	3		8	1
41	2026-07-30 13:27:20.895819+00	db030754-1d60-4524-b375-078107e4ef7e	Brian Kiprop	3		8	1
42	2026-07-30 13:27:20.898654+00	1fbef470-52b1-48cc-88eb-55d7a904651b	Daniel Mwangi	3		8	1
43	2026-07-30 13:27:20.903359+00	d89c423e-3961-4fa9-bcaa-86e2e4db6547	Esther Chebet	3		8	1
44	2026-07-30 13:27:20.909824+00	4f64f3a0-27d1-4e8d-9e23-df0de1625cc8	Fatima Hassan	3		8	1
45	2026-07-30 13:27:20.918461+00	41aa0f78-f681-4554-9af2-a982456c56a1	Grace Akinyi	3		8	1
46	2026-07-30 13:27:20.926449+00	18e9fa65-5582-415b-b56b-906bc953cc37	James Kiprono	3		8	1
47	2026-07-30 13:27:20.934399+00	4cbbac71-1f3b-4b38-bb1f-8b7d8d95519e	Kevin Mboya	3		8	1
48	2026-07-30 13:27:20.941439+00	ac4180dc-d23c-4d7d-897c-8b39e6aaf23b	Nancy Akoth	3		8	1
49	2026-07-30 13:27:20.944362+00	769b9355-a49d-40e5-9016-2d44a525eee9	Sarah Wanjiku	3		8	1
50	2026-07-30 13:28:43.224844+00	19a63d40-529b-4feb-b06d-5bf0d6a8b211	Peter Otieno	3		8	1
51	2026-07-30 13:35:09.907539+00	9a454fe5-cd90-4c0f-a241-03c85fabfc8b	Sylvia Chebwogen	2	[]	8	1
52	2026-07-30 13:35:49.057595+00	a2c94202-9ebf-46d3-90a7-f190fe4af593	Khadija Jelle	2	[{"changed": {"fields": ["Quote", "Photo"]}}]	8	1
53	2026-07-30 13:36:46.862381+00	7f58cb5b-99dd-46bb-a8ec-0ba22933a4c1	John Ndungu Kiarie	2	[{"changed": {"fields": ["Photo"]}}]	8	1
54	2026-07-30 13:37:23.176642+00	1030c692-a104-47e4-a2a5-7cc58b10c0ca	Samwel Chege Mwangi	2	[{"changed": {"fields": ["Photo"]}}]	8	1
55	2026-07-30 13:49:04.390757+00	552edbf3-adf7-4df4-ae07-b80ef44fc4ed	Byron Onyango Odongo	1	[{"added": {}}]	8	1
56	2026-07-30 13:55:58.58941+00	fc27774c-34b5-4968-982a-0e97aa610587	Ezra Mageto	1	[{"added": {}}]	8	1
57	2026-07-30 14:04:45.26529+00	dea270b2-62f7-449d-ab50-42d0c4655f6f	Jemmimah Kananu	1	[{"added": {}}]	8	1
58	2026-07-30 14:22:16.373833+00	4033544b-1732-4c48-a80e-b53310a28f2b	Peter  Njuguna	1	[{"added": {}}]	8	1
59	2026-07-30 14:30:43.542198+00	92a503de-8713-4680-a955-e3efe8e22af1	Nicole Alice	1	[{"added": {}}]	8	1
60	2026-07-30 14:36:34.77603+00	0dd031f5-df57-4106-a8f8-98c6c6f9359d	Irene  Yegon	1	[{"added": {}}]	8	1
61	2026-07-30 14:50:44.561845+00	bfe4c0f6-7354-4726-b4f6-cd792d96c440	Wendy Angela Anyango	1	[{"added": {}}]	8	1
62	2026-07-30 14:55:02.398695+00	806da3c2-cdcd-4bac-b89b-6139ef207d63	Adan Onyancha	1	[{"added": {}}]	8	1
63	2026-07-30 14:55:51.766545+00	9a454fe5-cd90-4c0f-a241-03c85fabfc8b	Sylvia Chebwogen	2	[{"changed": {"fields": ["Photo"]}}]	8	1
64	2026-07-30 18:49:51.824736+00	09c86958-4e09-4a49-bf6f-33808a84e518	Amina Said	3		8	1
65	2026-07-30 18:49:51.828559+00	db030754-1d60-4524-b375-078107e4ef7e	Brian Kiprop	3		8	1
66	2026-07-30 18:49:51.832964+00	1fbef470-52b1-48cc-88eb-55d7a904651b	Daniel Mwangi	3		8	1
67	2026-07-30 18:49:51.835548+00	d89c423e-3961-4fa9-bcaa-86e2e4db6547	Esther Chebet	3		8	1
68	2026-07-30 18:49:51.837975+00	4cbbac71-1f3b-4b38-bb1f-8b7d8d95519e	Kevin Mboya	3		8	1
69	2026-07-30 18:49:51.84038+00	ac4180dc-d23c-4d7d-897c-8b39e6aaf23b	Nancy Akoth	3		8	1
70	2026-07-30 18:49:51.842785+00	19a63d40-529b-4feb-b06d-5bf0d6a8b211	Peter Otieno	3		8	1
71	2026-07-30 18:49:51.845553+00	769b9355-a49d-40e5-9016-2d44a525eee9	Sarah Wanjiku	3		8	1
72	2026-07-30 18:52:08.994429+00	4f64f3a0-27d1-4e8d-9e23-df0de1625cc8	Fatima Hassan	3		8	1
73	2026-07-30 18:52:08.997096+00	41aa0f78-f681-4554-9af2-a982456c56a1	Grace Akinyi	3		8	1
74	2026-07-30 18:52:09.000016+00	18e9fa65-5582-415b-b56b-906bc953cc37	James Kiprono	3		8	1
75	2026-07-30 18:59:27.069023+00	23513902-8861-4ecf-8ada-ca0845b7c1db	Certification Preparation Programme	2	[{"changed": {"fields": ["Photo"]}}]	10	1
76	2026-07-30 19:00:16.56644+00	23513902-8861-4ecf-8ada-ca0845b7c1db	Certification Preparation Programme	2	[{"changed": {"fields": ["Activity date"]}}]	10	1
77	2026-07-30 19:02:49.152884+00	03dab206-dce2-4ef7-bf73-da60e7a2f5c3	Network Infrastructure Design Lab	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
78	2026-07-30 19:05:01.292712+00	3990dc8b-27c6-4640-917a-dde87b4eef67	OTDR and Power Meter Practical Sessions	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
79	2026-07-30 19:09:39.415741+00	376f4967-53c2-46d6-b61e-2241cb5f80e8	Safety and Compliance Training	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
80	2026-07-30 19:12:57.552318+00	3990dc8b-27c6-4640-917a-dde87b4eef67	OTDR and Power Meter Practical Sessions	2	[{"changed": {"fields": ["Photo"]}}]	10	1
81	2026-07-30 19:15:38.505412+00	04946275-e761-4519-9196-c41394b57168	Hands-on Fibre Optic Splicing Lab	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
82	2026-07-30 19:17:23.557727+00	4d39933a-b174-41e7-8c20-b23898e808ec	Portfolio Development Workshop	2	[{"changed": {"fields": ["Photo"]}}]	10	1
83	2026-07-30 19:24:31.393168+00	b717978a-81e6-438d-a32d-0e18a07e1af3	Industry Masterclasses with Leading Engineers	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
84	2026-07-30 19:26:12.655139+00	b5af62cd-b0d1-4032-b0ad-a4fd40b1bc40	Field Demonstrations at Active Deployment Sites	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
85	2026-07-30 19:29:14.480354+00	b717978a-81e6-438d-a32d-0e18a07e1af3	Industry Masterclasses with Leading Engineers	2	[{"changed": {"fields": ["Photo"]}}]	10	1
86	2026-07-30 19:31:58.60373+00	e1095eb6-ed61-4b88-9b62-c2cc54738d5b	Broadband Deployment and Last-Mile Connectivity	2	[{"changed": {"fields": ["Photo"]}}]	10	1
87	2026-07-30 19:32:21.519173+00	b5af62cd-b0d1-4032-b0ad-a4fd40b1bc40	Field Demonstrations at Active Deployment Sites	2	[{"changed": {"fields": ["Photo"]}}]	10	1
88	2026-07-31 09:14:54.335824+00	09c86958-4e09-4a49-bf6f-33808a84e518	Amina Said	3		8	1
89	2026-07-31 09:14:54.343529+00	db030754-1d60-4524-b375-078107e4ef7e	Brian Kiprop	3		8	1
90	2026-07-31 09:14:54.346531+00	1fbef470-52b1-48cc-88eb-55d7a904651b	Daniel Mwangi	3		8	1
91	2026-07-31 09:14:54.350138+00	d89c423e-3961-4fa9-bcaa-86e2e4db6547	Esther Chebet	3		8	1
92	2026-07-31 09:14:54.353671+00	4cbbac71-1f3b-4b38-bb1f-8b7d8d95519e	Kevin Mboya	3		8	1
93	2026-07-31 09:14:54.356524+00	ac4180dc-d23c-4d7d-897c-8b39e6aaf23b	Nancy Akoth	3		8	1
94	2026-07-31 09:14:54.360975+00	19a63d40-529b-4feb-b06d-5bf0d6a8b211	Peter Otieno	3		8	1
95	2026-07-31 09:14:54.363675+00	769b9355-a49d-40e5-9016-2d44a525eee9	Sarah Wanjiku	3		8	1
96	2026-07-31 09:16:08.934619+00	4f64f3a0-27d1-4e8d-9e23-df0de1625cc8	Fatima Hassan	3		8	1
97	2026-07-31 09:16:08.937961+00	41aa0f78-f681-4554-9af2-a982456c56a1	Grace Akinyi	3		8	1
98	2026-07-31 09:16:08.943089+00	18e9fa65-5582-415b-b56b-906bc953cc37	James Kiprono	3		8	1
99	2026-07-31 09:19:12.238687+00	22222222-2222-2222-2222-222222222202	JKUAT	2	[{"changed": {"fields": ["Focus areas", "Logo"]}}]	15	1
100	2026-07-31 09:20:05.268339+00	22222222-2222-2222-2222-222222222203	JHUB Africa	2	[{"changed": {"fields": ["Focus areas", "Logo"]}}]	15	1
101	2026-07-31 09:21:41.323148+00	23513902-8861-4ecf-8ada-ca0845b7c1db	Certification Preparation Programme	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
102	2026-07-31 09:22:41.861123+00	e1095eb6-ed61-4b88-9b62-c2cc54738d5b	Broadband Deployment and Last-Mile Connectivity	2	[{"changed": {"fields": ["Photo"]}}]	10	1
103	2026-07-31 09:23:07.31787+00	e1095eb6-ed61-4b88-9b62-c2cc54738d5b	Broadband Deployment and Last-Mile Connectivity	2	[{"changed": {"fields": ["Activity date"]}}]	10	1
104	2026-07-31 09:23:48.880252+00	3990dc8b-27c6-4640-917a-dde87b4eef67	OTDR and Power Meter Practical Sessions	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
105	2026-07-31 09:24:26.761126+00	376f4967-53c2-46d6-b61e-2241cb5f80e8	Safety and Compliance Training	2	[{"changed": {"fields": ["Photo"]}}]	10	1
106	2026-07-31 09:25:24.012182+00	04946275-e761-4519-9196-c41394b57168	Hands-on Fibre Optic Splicing Lab	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
107	2026-07-31 09:26:06.587946+00	4d39933a-b174-41e7-8c20-b23898e808ec	Portfolio Development Workshop	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
108	2026-07-31 09:26:49.066209+00	b717978a-81e6-438d-a32d-0e18a07e1af3	Industry Masterclasses with Leading Engineers	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
109	2026-07-31 09:27:35.609884+00	b5af62cd-b0d1-4032-b0ad-a4fd40b1bc40	Field Demonstrations at Active Deployment Sites	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
110	2026-07-31 09:28:10.705379+00	03dab206-dce2-4ef7-bf73-da60e7a2f5c3	Network Infrastructure Design Lab	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
111	2026-07-31 10:03:30.340683+00	5c00bf4e-c9f2-4962-bd6b-fc89dcb821f2	Cohort 1 Trainees Begin Industry Attachments Across Kenya	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
112	2026-07-31 10:04:14.454667+00	227200d2-661d-40f0-9e84-581b024ab10b	Community Outreach: Digital Literacy Workshop in Kiambu County	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
113	2026-07-31 10:08:24.910428+00	8f026c8a-d01d-4f69-a1ff-47b250d67269	Industry Mentors Share Insights on Kenya's Digital Infrastructure Future	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
114	2026-07-31 10:09:00.607058+00	f0b17c7a-97f6-4728-bb29-32fe4c5946c9	Field Visit: Trainees Experience Real-World Fibre Deployment	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
115	2026-07-31 10:10:28.485148+00	92955bcd-2c31-49f8-9832-1543984d2666	Women in Tech: Breaking Barriers in Network Infrastructure	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
116	2026-07-31 10:11:51.3686+00	4378ba73-d2a3-48d8-87d7-345d2d272a22	JKUAT and JHUB Africa Sign MoU to Expand Digital Skills Programme	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
117	2026-07-31 10:13:39.311214+00	efcefd86-67b8-4402-aedc-5f519b619324	Trainees Complete First Round of Fibre Optic Splice Certification	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
118	2026-07-31 10:14:09.62167+00	40d07af2-fadc-470f-a103-f9fe64fafd49	Why Fibre Optics is the Next Frontier for Kenya's Youth	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
119	2026-07-31 10:19:02.185343+00	2791f15a-e70d-4164-baa5-b4671c06cea9	Kenya Pipeline Foundation Commits to Digital Skills Development	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
120	2026-07-31 10:21:22.839582+00	e0adf7d8-a851-487a-ae5d-3cac74b07116	Inuka Digital Leap First Cohort of 15 Trailblazers	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
121	2026-07-31 11:09:21.83289+00	09c86958-4e09-4a49-bf6f-33808a84e518	Amina Said	3		8	1
122	2026-07-31 11:09:21.838477+00	db030754-1d60-4524-b375-078107e4ef7e	Brian Kiprop	3		8	1
123	2026-07-31 11:09:21.841259+00	1fbef470-52b1-48cc-88eb-55d7a904651b	Daniel Mwangi	3		8	1
124	2026-07-31 11:09:21.843994+00	d89c423e-3961-4fa9-bcaa-86e2e4db6547	Esther Chebet	3		8	1
125	2026-07-31 11:09:21.852062+00	4cbbac71-1f3b-4b38-bb1f-8b7d8d95519e	Kevin Mboya	3		8	1
126	2026-07-31 11:09:21.859897+00	ac4180dc-d23c-4d7d-897c-8b39e6aaf23b	Nancy Akoth	3		8	1
127	2026-07-31 11:09:21.864635+00	19a63d40-529b-4feb-b06d-5bf0d6a8b211	Peter Otieno	3		8	1
128	2026-07-31 11:09:21.868833+00	769b9355-a49d-40e5-9016-2d44a525eee9	Sarah Wanjiku	3		8	1
129	2026-07-31 11:10:01.186639+00	4f64f3a0-27d1-4e8d-9e23-df0de1625cc8	Fatima Hassan	3		8	1
130	2026-07-31 11:10:01.204522+00	41aa0f78-f681-4554-9af2-a982456c56a1	Grace Akinyi	3		8	1
131	2026-07-31 11:10:01.238894+00	18e9fa65-5582-415b-b56b-906bc953cc37	James Kiprono	3		8	1
132	2026-07-31 11:18:51.980867+00	227200d2-661d-40f0-9e84-581b024ab10b	Community Outreach: Digital Literacy Workshop in Kiambu County	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
133	2026-07-31 11:19:06.640682+00	5c00bf4e-c9f2-4962-bd6b-fc89dcb821f2	Cohort 1 Trainees Begin Industry Attachments Across Kenya	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
134	2026-07-31 11:19:28.531368+00	8f026c8a-d01d-4f69-a1ff-47b250d67269	Industry Mentors Share Insights on Kenya's Digital Infrastructure Future	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
135	2026-07-31 11:19:45.914211+00	f0b17c7a-97f6-4728-bb29-32fe4c5946c9	Field Visit: Trainees Experience Real-World Fibre Deployment	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
136	2026-07-31 11:20:43.642183+00	92955bcd-2c31-49f8-9832-1543984d2666	Women in Tech: Breaking Barriers in Network Infrastructure	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
137	2026-07-31 11:21:05.741725+00	4378ba73-d2a3-48d8-87d7-345d2d272a22	JKUAT and JHUB Africa Sign MoU to Expand Digital Skills Programme	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
138	2026-07-31 11:21:26.303658+00	efcefd86-67b8-4402-aedc-5f519b619324	Trainees Complete First Round of Fibre Optic Splice Certification	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
139	2026-07-31 11:22:14.455625+00	40d07af2-fadc-470f-a103-f9fe64fafd49	Why Fibre Optics is the Next Frontier for Kenya's Youth	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
140	2026-07-31 11:22:45.743539+00	2791f15a-e70d-4164-baa5-b4671c06cea9	Kenya Pipeline Foundation Commits to Digital Skills Development	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
141	2026-07-31 11:23:05.552934+00	e0adf7d8-a851-487a-ae5d-3cac74b07116	Inuka Digital Leap First Cohort of 15 Trailblazers	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
142	2026-07-31 11:26:04.027656+00	5c00bf4e-c9f2-4962-bd6b-fc89dcb821f2	Cohort 1 Trainees Begin Industry Attachments Across Kenya	2	[{"changed": {"fields": ["Cover image"]}}]	13	1
143	2026-07-31 11:26:48.127061+00	23513902-8861-4ecf-8ada-ca0845b7c1db	Certification Preparation Programme	2	[{"changed": {"fields": ["Photo"]}}]	10	1
144	2026-07-31 11:27:02.871456+00	23513902-8861-4ecf-8ada-ca0845b7c1db	Certification Preparation Programme	2	[{"changed": {"fields": ["Activity date"]}}]	10	1
145	2026-07-31 11:27:23.31482+00	3990dc8b-27c6-4640-917a-dde87b4eef67	OTDR and Power Meter Practical Sessions	2	[{"changed": {"fields": ["Photo"]}}]	10	1
146	2026-07-31 11:27:52.339859+00	376f4967-53c2-46d6-b61e-2241cb5f80e8	Safety and Compliance Training	2	[{"changed": {"fields": ["Photo"]}}]	10	1
147	2026-07-31 11:28:57.613758+00	04946275-e761-4519-9196-c41394b57168	Hands-on Fibre Optic Splicing Lab	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
148	2026-07-31 11:29:32.643819+00	4d39933a-b174-41e7-8c20-b23898e808ec	Portfolio Development Workshop	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
149	2026-07-31 11:30:14.677981+00	b717978a-81e6-438d-a32d-0e18a07e1af3	Industry Masterclasses with Leading Engineers	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
150	2026-07-31 11:30:39.507295+00	b5af62cd-b0d1-4032-b0ad-a4fd40b1bc40	Field Demonstrations at Active Deployment Sites	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
151	2026-07-31 11:31:35.708339+00	03dab206-dce2-4ef7-bf73-da60e7a2f5c3	Network Infrastructure Design Lab	2	[{"changed": {"fields": ["Activity date", "Photo"]}}]	10	1
152	2026-07-31 11:32:04.073271+00	e1095eb6-ed61-4b88-9b62-c2cc54738d5b	Broadband Deployment and Last-Mile Connectivity	2	[{"changed": {"fields": ["Photo"]}}]	10	1
153	2026-07-31 11:33:26.201216+00	22222222-2222-2222-2222-222222222202	JKUAT	2	[{"changed": {"fields": ["Focus areas", "Logo"]}}]	15	1
154	2026-07-31 11:33:45.658105+00	22222222-2222-2222-2222-222222222203	JHUB Africa	2	[{"changed": {"fields": ["Focus areas", "Logo"]}}]	15	1
155	2026-07-31 12:33:41.400184+00	9a454fe5-cd90-4c0f-a241-03c85fabfc8b	Sylvia Chebwogen	2	[{"changed": {"fields": ["Photo"]}}]	8	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	cohorts	cohort
8	cohorts	fellow
9	cohorts	certification
10	activities	activity
11	content	sitesetting
12	content	galleryitem
13	content	post
14	impact	metric
15	partners	partner
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	cohorts	0001_initial	2026-07-17 08:42:59.363931+00
2	activities	0001_initial	2026-07-17 08:42:59.445015+00
3	contenttypes	0001_initial	2026-07-17 08:42:59.467313+00
4	auth	0001_initial	2026-07-17 08:42:59.743489+00
5	admin	0001_initial	2026-07-17 08:42:59.824274+00
6	admin	0002_logentry_remove_auto_add	2026-07-17 08:42:59.839814+00
7	admin	0003_logentry_add_action_flag_choices	2026-07-17 08:42:59.854346+00
8	contenttypes	0002_remove_content_type_name	2026-07-17 08:42:59.932404+00
9	auth	0002_alter_permission_name_max_length	2026-07-17 08:43:00.021375+00
10	auth	0003_alter_user_email_max_length	2026-07-17 08:43:00.038234+00
11	auth	0004_alter_user_username_opts	2026-07-17 08:43:00.04602+00
12	auth	0005_alter_user_last_login_null	2026-07-17 08:43:00.152963+00
13	auth	0006_require_contenttypes_0002	2026-07-17 08:43:00.157422+00
14	auth	0007_alter_validators_add_error_messages	2026-07-17 08:43:00.183716+00
15	auth	0008_alter_user_username_max_length	2026-07-17 08:43:00.227176+00
16	auth	0009_alter_user_last_name_max_length	2026-07-17 08:43:00.250504+00
17	auth	0010_alter_group_name_max_length	2026-07-17 08:43:00.328884+00
18	auth	0011_update_proxy_permissions	2026-07-17 08:43:00.354248+00
19	auth	0012_alter_user_first_name_max_length	2026-07-17 08:43:00.427223+00
20	content	0001_initial	2026-07-17 08:43:00.605662+00
21	content	0002_alter_post_slug	2026-07-17 08:43:00.631624+00
22	impact	0001_initial	2026-07-17 08:43:00.64779+00
23	partners	0001_initial	2026-07-17 08:43:00.658876+00
24	partners	0002_partner_focus_areas	2026-07-17 08:43:00.670173+00
25	sessions	0001_initial	2026-07-17 08:43:00.741518+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
oow2ts77tfgmx4ghfaw8ntyxcb4zb0z7	.eJxVjEEOwiAQRe_C2hAoMjAu3XsGAsxgqwaS0q6MdzckXej2v_f-W4S4b3PYO69hIXERWpx-txTzk-sA9Ij13mRudVuXJIciD9rlrRG_rof7dzDHPo_aMkImFU2Z2BBAScYpBZhQuwyl0DSRJURyzmso6JPHM3AytrBVID5f8yU3_w:1wkeZx:sPUX2IPrVDrQ6DmmOXb9kcxpyG3dMe9twbKMpZmibag	2026-07-31 09:09:57.879768+00
lhm5m75yt5fzqhngtcq4j4mx7o3hsadz	.eJxVjEEOwiAQRe_C2hAoMjAu3XsGAsxgqwaS0q6MdzckXej2v_f-W4S4b3PYO69hIXERWpx-txTzk-sA9Ij13mRudVuXJIciD9rlrRG_rof7dzDHPo_aMkImFU2Z2BBAScYpBZhQuwyl0DSRJURyzmso6JPHM3AytrBVID5f8yU3_w:1wlngO:-fBePELboN6CidkUIYNV8FOg4sa866Rj48w-1KckRuk	2026-08-03 13:05:20.318292+00
hhyqh52kjxoc9vtelzi69w557n0qm83r	.eJxVjEEOwiAQRe_C2hAoMjAu3XsGAsxgqwaS0q6MdzckXej2v_f-W4S4b3PYO69hIXERWpx-txTzk-sA9Ij13mRudVuXJIciD9rlrRG_rof7dzDHPo_aMkImFU2Z2BBAScYpBZhQuwyl0DSRJURyzmso6JPHM3AytrBVID5f8yU3_w:1wpjJd:RNAM9hvsk-m8ZIlWUxx2L1zxY2gmqsVZcgIwNAR8b2g	2026-08-14 09:14:05.145375+00
mlmcxjxwq84ezxuog3edvmzio9dqe4y5	.eJxVjEEOwiAQRe_C2hAoMjAu3XsGAsxgqwaS0q6MdzckXej2v_f-W4S4b3PYO69hIXERWpx-txTzk-sA9Ij13mRudVuXJIciD9rlrRG_rof7dzDHPo_aMkImFU2Z2BBAScYpBZhQuwyl0DSRJURyzmso6JPHM3AytrBVID5f8yU3_w:1wqmCM:p6l-WVTVY4zZ-1Lamf6faqbj0T7StwWJp81RJwp5mfs	2026-08-17 06:30:54.100016+00
\.


--
-- Data for Name: impact_metric; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.impact_metric (id, key, label, value, unit, sort_order, updated_at) FROM stdin;
11111111-1111-1111-1111-111111111101	total_trainees	Total Trainees	15	trainees	1	2026-07-06 00:00:00+00
11111111-1111-1111-1111-111111111102	training_duration	Training Duration	3	months	2	2026-07-06 00:00:00+00
11111111-1111-1111-1111-111111111103	attachment_duration	Attachment Duration	3	months	3	2026-07-06 00:00:00+00
11111111-1111-1111-1111-111111111104	certifications_supported	Certifications Supported	4	certifications	4	2026-07-06 00:00:00+00
11111111-1111-1111-1111-111111111105	masterclasses	Masterclasses Delivered	5	sessions	5	2026-07-06 00:00:00+00
11111111-1111-1111-1111-111111111106	employment_tracking	Employment Tracking Period	12	months	6	2026-07-06 00:00:00+00
\.


--
-- Data for Name: partners_partner; Type: TABLE DATA; Schema: public; Owner: inuka_db_user
--

COPY public.partners_partner (id, name, role, description, logo, website_url, is_required_acknowledgement, sort_order, focus_areas) FROM stdin;
22222222-2222-2222-2222-222222222201	Kenya Pipeline Company Foundation	Corporate Foundation	The Kenya Pipeline Company Foundation champions corporate social responsibility by funding digital skills development programmes that create sustainable economic opportunities for Kenyan youth.	partners/Logo_of_KPC_uwwemu	https://www.kpcfoundation.or.ke/	t	1	Programme Funding, Industry Equipment, Youth Empowerment, Infrastructure Support
22222222-2222-2222-2222-222222222202	JKUAT	Academic Partner	Jomo Kenyatta University of Agriculture and Technology	partners/jkuat_infze5	https://www.jkuat.ac.ke	f	2	Curriculum Development, Accredited Certification, Research & Innovation, Training Facilities
22222222-2222-2222-2222-222222222203	JHUB Africa	Implementation Partner	Innovation hub driving digital transformation across Africa	partners/jhub-africa_til6vl	https://www.jhubafrica.com	f	3	Programme Management, Technical Training, Industry Partnerships, Trainee Placement
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inuka_db_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inuka_db_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inuka_db_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inuka_db_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inuka_db_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inuka_db_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inuka_db_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 155, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inuka_db_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inuka_db_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: activities_activity activities_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.activities_activity
    ADD CONSTRAINT activities_activity_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: cohorts_certification cohorts_certification_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.cohorts_certification
    ADD CONSTRAINT cohorts_certification_pkey PRIMARY KEY (id);


--
-- Name: cohorts_cohort cohorts_cohort_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.cohorts_cohort
    ADD CONSTRAINT cohorts_cohort_pkey PRIMARY KEY (id);


--
-- Name: cohorts_fellow cohorts_fellow_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.cohorts_fellow
    ADD CONSTRAINT cohorts_fellow_pkey PRIMARY KEY (id);


--
-- Name: content_galleryitem content_galleryitem_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.content_galleryitem
    ADD CONSTRAINT content_galleryitem_pkey PRIMARY KEY (id);


--
-- Name: content_post content_post_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.content_post
    ADD CONSTRAINT content_post_pkey PRIMARY KEY (id);


--
-- Name: content_post content_post_slug_key; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.content_post
    ADD CONSTRAINT content_post_slug_key UNIQUE (slug);


--
-- Name: content_sitesetting content_sitesetting_key_key; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.content_sitesetting
    ADD CONSTRAINT content_sitesetting_key_key UNIQUE (key);


--
-- Name: content_sitesetting content_sitesetting_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.content_sitesetting
    ADD CONSTRAINT content_sitesetting_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: impact_metric impact_metric_key_key; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.impact_metric
    ADD CONSTRAINT impact_metric_key_key UNIQUE (key);


--
-- Name: impact_metric impact_metric_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.impact_metric
    ADD CONSTRAINT impact_metric_pkey PRIMARY KEY (id);


--
-- Name: partners_partner partners_partner_pkey; Type: CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.partners_partner
    ADD CONSTRAINT partners_partner_pkey PRIMARY KEY (id);


--
-- Name: activities_activity_cohort_id_cac5646a; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX activities_activity_cohort_id_cac5646a ON public.activities_activity USING btree (cohort_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: cohorts_certification_fellow_id_741a4bd7; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX cohorts_certification_fellow_id_741a4bd7 ON public.cohorts_certification USING btree (fellow_id);


--
-- Name: cohorts_fellow_cohort_id_e7d10245; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX cohorts_fellow_cohort_id_e7d10245 ON public.cohorts_fellow USING btree (cohort_id);


--
-- Name: content_galleryitem_cohort_id_29f6be5f; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX content_galleryitem_cohort_id_29f6be5f ON public.content_galleryitem USING btree (cohort_id);


--
-- Name: content_post_author_id_a90965c2; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX content_post_author_id_a90965c2 ON public.content_post USING btree (author_id);


--
-- Name: content_post_slug_efa80cd5_like; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX content_post_slug_efa80cd5_like ON public.content_post USING btree (slug varchar_pattern_ops);


--
-- Name: content_sitesetting_key_0508b562_like; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX content_sitesetting_key_0508b562_like ON public.content_sitesetting USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: impact_metric_key_617f71fd_like; Type: INDEX; Schema: public; Owner: inuka_db_user
--

CREATE INDEX impact_metric_key_617f71fd_like ON public.impact_metric USING btree (key varchar_pattern_ops);


--
-- Name: activities_activity activities_activity_cohort_id_cac5646a_fk_cohorts_cohort_id; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.activities_activity
    ADD CONSTRAINT activities_activity_cohort_id_cac5646a_fk_cohorts_cohort_id FOREIGN KEY (cohort_id) REFERENCES public.cohorts_cohort(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cohorts_certification cohorts_certification_fellow_id_741a4bd7_fk_cohorts_fellow_id; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.cohorts_certification
    ADD CONSTRAINT cohorts_certification_fellow_id_741a4bd7_fk_cohorts_fellow_id FOREIGN KEY (fellow_id) REFERENCES public.cohorts_fellow(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cohorts_fellow cohorts_fellow_cohort_id_e7d10245_fk_cohorts_cohort_id; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.cohorts_fellow
    ADD CONSTRAINT cohorts_fellow_cohort_id_e7d10245_fk_cohorts_cohort_id FOREIGN KEY (cohort_id) REFERENCES public.cohorts_cohort(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: content_galleryitem content_galleryitem_cohort_id_29f6be5f_fk_cohorts_cohort_id; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.content_galleryitem
    ADD CONSTRAINT content_galleryitem_cohort_id_29f6be5f_fk_cohorts_cohort_id FOREIGN KEY (cohort_id) REFERENCES public.cohorts_cohort(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: content_post content_post_author_id_a90965c2_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.content_post
    ADD CONSTRAINT content_post_author_id_a90965c2_fk_auth_user_id FOREIGN KEY (author_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: inuka_db_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: FUNCTION pg_stat_statements(showtext boolean, OUT userid oid, OUT dbid oid, OUT toplevel boolean, OUT queryid bigint, OUT query text, OUT plans bigint, OUT total_plan_time double precision, OUT min_plan_time double precision, OUT max_plan_time double precision, OUT mean_plan_time double precision, OUT stddev_plan_time double precision, OUT calls bigint, OUT total_exec_time double precision, OUT min_exec_time double precision, OUT max_exec_time double precision, OUT mean_exec_time double precision, OUT stddev_exec_time double precision, OUT rows bigint, OUT shared_blks_hit bigint, OUT shared_blks_read bigint, OUT shared_blks_dirtied bigint, OUT shared_blks_written bigint, OUT local_blks_hit bigint, OUT local_blks_read bigint, OUT local_blks_dirtied bigint, OUT local_blks_written bigint, OUT temp_blks_read bigint, OUT temp_blks_written bigint, OUT shared_blk_read_time double precision, OUT shared_blk_write_time double precision, OUT local_blk_read_time double precision, OUT local_blk_write_time double precision, OUT temp_blk_read_time double precision, OUT temp_blk_write_time double precision, OUT wal_records bigint, OUT wal_fpi bigint, OUT wal_bytes numeric, OUT wal_buffers_full bigint, OUT jit_functions bigint, OUT jit_generation_time double precision, OUT jit_inlining_count bigint, OUT jit_inlining_time double precision, OUT jit_optimization_count bigint, OUT jit_optimization_time double precision, OUT jit_emission_count bigint, OUT jit_emission_time double precision, OUT jit_deform_count bigint, OUT jit_deform_time double precision, OUT parallel_workers_to_launch bigint, OUT parallel_workers_launched bigint, OUT stats_since timestamp with time zone, OUT minmax_stats_since timestamp with time zone); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.pg_stat_statements(showtext boolean, OUT userid oid, OUT dbid oid, OUT toplevel boolean, OUT queryid bigint, OUT query text, OUT plans bigint, OUT total_plan_time double precision, OUT min_plan_time double precision, OUT max_plan_time double precision, OUT mean_plan_time double precision, OUT stddev_plan_time double precision, OUT calls bigint, OUT total_exec_time double precision, OUT min_exec_time double precision, OUT max_exec_time double precision, OUT mean_exec_time double precision, OUT stddev_exec_time double precision, OUT rows bigint, OUT shared_blks_hit bigint, OUT shared_blks_read bigint, OUT shared_blks_dirtied bigint, OUT shared_blks_written bigint, OUT local_blks_hit bigint, OUT local_blks_read bigint, OUT local_blks_dirtied bigint, OUT local_blks_written bigint, OUT temp_blks_read bigint, OUT temp_blks_written bigint, OUT shared_blk_read_time double precision, OUT shared_blk_write_time double precision, OUT local_blk_read_time double precision, OUT local_blk_write_time double precision, OUT temp_blk_read_time double precision, OUT temp_blk_write_time double precision, OUT wal_records bigint, OUT wal_fpi bigint, OUT wal_bytes numeric, OUT wal_buffers_full bigint, OUT jit_functions bigint, OUT jit_generation_time double precision, OUT jit_inlining_count bigint, OUT jit_inlining_time double precision, OUT jit_optimization_count bigint, OUT jit_optimization_time double precision, OUT jit_emission_count bigint, OUT jit_emission_time double precision, OUT jit_deform_count bigint, OUT jit_deform_time double precision, OUT parallel_workers_to_launch bigint, OUT parallel_workers_launched bigint, OUT stats_since timestamp with time zone, OUT minmax_stats_since timestamp with time zone) TO inuka_db_user;


--
-- Name: FUNCTION pg_stat_statements_info(OUT dealloc bigint, OUT stats_reset timestamp with time zone); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.pg_stat_statements_info(OUT dealloc bigint, OUT stats_reset timestamp with time zone) TO inuka_db_user;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO inuka_db_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO inuka_db_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO inuka_db_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO inuka_db_user;


--
-- PostgreSQL database dump complete
--

\unrestrict oSxrlaEtyREfc0kg0kDdyM7hdhTXEuIAvTJy0RP7N08qmjK8edxgUGzrDOz8rJU

